[build-system]
requires = ["uv_build>=0.12.3,<0.13"]
build-backend = "uv_build"

[project]
name = "autopost"
version = "0.0.11"
description = "Auto-posts social media updates"
readme = "README.md"
license = { file = "LICENSE" }
authors = [{ name = "William Woodruff", email = "william@yossarian.net" }]
classifiers = [
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3",
  "Development Status :: 4 - Beta",
  "Intended Audience :: Developers",
  "Topic :: Security",
]
requires-python = ">=3.14"

dependencies = [
  "atproto ~= 0.0.30",
  "feedparser ~= 6.0",
  "praw >= 7.6.1,< 8.1.0",
  "Mastodon.py >= 1.7,< 2.3",
  "pydantic >= 1.10,< 3.0",
  "python-frontmatter ~= 1.0",
  "result ~= 0.8",
  "rich >= 12.5.1,< 15.1.0",
  "python-twitter ~= 3.5",
]

[dependency-groups]
dev = [
    "ruff>=0.16.1",
    "ty>=0.0.65",
]


[project.urls]
Homepage = "https://pypi.org/project/autopost/"
Issues = "https://github.com/woodruffw/autopost/issues"
Source = "https://github.com/woodruffw/autopost"

[project.scripts]
autopost = "autopost._cli:main"

[tool.uv]
exclude-newer = "P7D"

[tool.ruff.lint]
ignore = ["BLE001"]
