on:
  release:
    types:
      - published

name: release

permissions: {}

jobs:
  pypi:
    name: upload release to PyPI
    runs-on: ubuntu-latest
    permissions:
      # Used for OIDC publishing + attestations.
      id-token: write

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: ">= 3.10"

    - name: deps
      run: python -m pip install -U build

    - name: build
      run: python -m build

    - name: publish
      uses: pypa/gh-action-pypi-publish@v1.12.2
      with:
        attestations: true

